错误日志

```
class ErrorLog(db.Model):
    __tablename__ = 'errorlog'

    id = db.Column(db.Integer, primary_key=True)
    errorname = db.Column(db.String(100), nullable=False, server_default=db.FetchedValue(), info='错误名称')
    erroranalysis = db.Column(db.String(500), nullable=False, server_default=db.FetchedValue(), info='错误解析')
    solution = db.Column(db.String(500), nullable=False, server_default=db.FetchedValue(), info='解决方案')
    category = db.Column(db.Integer, nullable=False, server_default=db.FetchedValue(), info='类别标识')
    updated_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), info='最后一次更新时间')
    created_time = db.Column(db.DateTime, nullable=False, server_default=db.FetchedValue(), info='插入时间')

```

时间：2020/2/5

错误名称：

```
Warning: (1366, "Incorrect string value: '\\xD6\\xD0\\xB9\\xFA\\xB1\\xEA...' for column 'VARIABLE_VALUE' at row 519")
```

错误原因：

```
这是mysql的编码问题，我这个问题出现的环境是windows系统，
mysql  Ver 8.0.13 for Win64 on x86_64 (MySQL Community Server - GPL)
python3.6.8
```

解决办法：

```
查看mysql的编码
show variables like 'character_set%';

```



时间：2020/2/8

错误名称：

```
ModuleNotFoundError: No module named 'MySQLdb'
```

错误原因：

```
sqlalchemy的默认连接mysql服务器的库是MySQLdb，而不是pymysql，但是mysqldb是python2版本的，在python3使用pymysql。
```

解决办法：

```
在python环境下，找到下面这个文件
flask_demo/lib/python3.6/site-packages/sqlalchemy/dialects/mysql/mysqldb.py

添加下面两行代码
import pymysql
pymysql.install_as_MySQLdb()
```



时间:2020/2/8

错误名称

```
FileNotFoundError: [Errno 2] No such file or directory: 'common/models/log/AppAccessLog.py'
```

错误原因：

```
这里有两种情况：
1.通常情况下，是你找不到文件或者是目录
2.这是特定情况，我在生成模型类的时候出的错
flask-sqlacodegen 'mysql://root:mysql0220@127.0.0.1/food_db' --tables app_access_log --outfile "common/models/log/AppAccessLog.py" --flask
原因是没有log目录
```

解决办法：

```
在models目录下新建log目录，
```



时间:2020/2/13

错误名称：

```
jinja2.exceptions.TemplateNotFound: user/login.html
```

错误原因：

```
视图函数找不到模板文件--->render_template('user/login.html')
```

解决办法：

```
排查是否文件不存在还是路径配置错了，flask默认的template路径就是启动文件的当前路径下的template目录。
```



时间:2020/2/13

错误名称：

```
jinja2.exceptions.UndefinedError: 'buildStaticUrl' is undefined
```

错误原因：

```
模板文件里有使用buildStaticUrl方法，但是你没有定义这个方法
```

解决办法：

```
定义一个url匹配文件，
UrlManager.py
# -*- coding: utf-8 -*-

class UrlManager(object):
    def __init__(self):
        pass

    @staticmethod
    def buildUrl( path ):
        return path

    @staticmethod
    def buildStaticUrl(path):
        ver = "%s"%( 22222222 )
        path =  "/static" + path + "?ver=" + ver
        return UrlManager.buildUrl( path )
```

```
# 使用
# 如何在模板文件里调用这些方法
"""
函数模板
"""
from common.libs.UrlManager import UrlManager
app.add_template_global(UrlManager.buildStaticUrl, 'buildStaticUrl')
app.add_template_global(UrlManager.buildUrl, 'buildUrl')
```



日期：2020/02/14

错误名称：

```
192.168.153.153 redirected you too many times.
```

错误原因：

```
这个页面重定向太多次
这是因为定义拦截器的时候，没有过滤掉静态文件的路由请求和login页面的请求，
如果登录页面需要登录的话就进入死循环了。
```

解决办法：

```
过滤掉不需要拦截的路由
import re
print('pattern', '%s' % "|".join(ignore_check_login_urls))
pattern = re.compile('%s' % "|".join(ignore_check_login_urls))
if pattern.match(path):
	return
print('pattern', '%s' % "|".join(ignore_urls))
pattern = re.compile('%s' % "|".join(ignore_urls))
if pattern.match(path):
	return
```





错误名称：

```
jinja2.exceptions.UndefinedError: 'current_user' is undefined
```

错误原因：

```
渲染模板时发现没有current_user，
```

解决办法：

```
如果在每个视图函数里都写上current_user就很麻烦，所以直接修改渲染模板的函数

```



时间：2020/02/18

错误名称：

```
Bad Request
The browser (or proxy) sent a request that this server could not understand.
```

错误解析：

```
错误的请求
浏览器（或代理）发送了一个此服务器无法理解的请求。
虽然解释就是这样，但是这个问题发生在flask搭建微信小程序订餐系统第九章会员管理的index页面上，原因仅仅只是代码写错了，
if 'status' in req and int(req['status']) > -1:
	query = query.filter(Member.status == int(req['ststus']))
```

解决方法：

```
仅仅需要把错误参数写成正确参数就行了
query = query.filter(Member.status == int(req['status']))
```



错误名称：

```
后台配置项返回格式出错，上传功能将不能正常使用！
```

错误解析：

```
ueditor接收到请求要返回配置信息，
```



错误名称：

```
TypeError: Object of type 'Image' is not JSON serializable

```

错误解析：

```
类型错误：“Image”类型的对象不是JSON可序列化的
```

解决办法：

```
只是代码写错了，要传递列表，却传递了数据库查询出的对象
```



2020/02/25

错误名称：

```
In aggregated query without GROUP BY, expression #1 of SELECT list contains nonaggregated column 'food_db.pay_order.id'; this is incompatible with sql_mode=only_full_group_by")
```

错误解析：

```
“在不带GROUP BY的聚合查询中，不带GROUP BY的聚合查询中的表达式1，选择列表的表达式1包含未聚合的列'food db.pay_order.id'；这与sql_mode=only_full_GROUP_BY'不兼容”

在MySQL5.7.5后，默认开启了ONLY_FULL_GROUP_BY，所以导致了之前的一些SQL无法正常执行，其实，是我们的SQL不规范造成的，因为group by 之后，返回的一些数据是不确定的，所以才会出现这个错误。
```

解决方案：

```
https://blog.csdn.net/qq_26365837/article/details/88020755
mysql -uroot -p
show variables like '%sql_mode';
vim /etc/mysql/mysqld.d/mysqld.cnf
sql-mode=ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION
```

![image-20200225015451454](/home/jarvis/.config/Typora/typora-user-images/image-20200225015451454.png)





错误名称

```
sqlalchemy.orm.exc.UnmappedInstanceError: Class 'flask_sqlalchemy._BoundDeclarativeMeta' is not mapped; was a class (common.models.stat.StatDailyMember.StatDailyMember) supplied where an instance was required?
2020-02-25 15:22:00,529 INFO sqlalchemy.engine.base.Engine ROLLBACK
```

错误解析

```
声明的模型类没有实例化
tmp_model_stat_member = StatDailyMember
```

解决办法

```
tmp_model_stat_member = StatDailyMember()
```

